#theme: jekyll-theme-cayman
remote_theme: nrandecker/particle

# Site settings
title: Benjamin J. Thompson
description: A blog about lorem ipsum dolor sit amet
baseurl: "/" # the subpath of your site, e.g. /blog
url: "praxeo.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Benjamin Thompson
user_description: I am a software developer specializing in web development, data integrations, automation and Linux system administration.
user_title: Software Developer
email: anon@anon.com
twitter_username: benj_thompson
github_username:  praxeo
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
